apiVersion: v1
kind: ConfigMap
metadata:
  name: video-config
data:
  REDIS_URL: "redis://redis:6379"
  POSTGRES: "postgresql://postgres:postgres@postgres:5432/postgres?connect_timeout=300"
  OAUTH_GOOGLE_CLIENT: "client"
  OAUTH_GOOGLE_SECRET: "secret"
  AUTH_DOMAIN: "peerprep.dev/user"
